// Runtime Certification pipeline (`npm run verify:runtime`).
// Runs the full battery of runtime checks and writes a reproducible certificate
// to docs/runtime-certification.md. Each step is PASS / FAIL / SKIP (SKIP only
// for live-DB steps when no database is reachable — never silently for code
// checks). Exit non-zero if any non-skipped step fails. Zero third-party deps.
import { spawnSync, execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const ROOT = process.cwd();
const node = process.execPath;

function run(cmd, args, { allowSkipOnDbError = false } = {}) {
  const r = spawnSync(cmd, args, { cwd: ROOT, encoding: 'utf8', timeout: 180_000 });
  const out = `${r.stdout ?? ''}${r.stderr ?? ''}`.trim();
  let status = r.status === 0 ? 'PASS' : 'FAIL';
  if (status === 'FAIL' && allowSkipOnDbError &&
      /ECONNREFUSED|ENOTFOUND|connect|authentication|timeout|closed/i.test(out)) {
    status = 'SKIP';
  }
  return { status, out };
}

const git = (() => { try { return execSync('git rev-parse --short HEAD').toString().trim(); } catch { return 'unknown'; } })();

const steps = [
  ['Import smoke (every package entrypoint)', () => run(node, ['scripts/audit/import-smoke.mjs', '.'])],
  ['Circular dependency scan',                () => run(node, ['scripts/audit/circular-scan.mjs', '.'])],
  ['API stability (live HTTP pipeline)',       () => run(node, ['scripts/audit/api-smoke.mjs'])],
  ['Plugin config validation',                 () => run(node, ['scripts/audit/plugin-config.mjs'])],
  ['Official plugin signatures (18/18)',       () => run(node, ['scripts/verify-official-signatures.mjs'])],
  ['PostgreSQL lifecycle + socket cleanup',    () => run(node, ['scripts/audit/pg-leak-probe.mjs'], { allowSkipOnDbError: true })],
  ['MySQL lifecycle + socket cleanup',         () => run(node, ['scripts/audit/mysql-leak-probe.mjs'], { allowSkipOnDbError: true })],
  ['SQLite lifecycle (tx + rollback)',         () => run(node, ['scripts/audit/sqlite-lifecycle.mjs'])],
  ['Memory: 20× startup/shutdown cycle drift', () => run(node, ['--expose-gc', 'scripts/audit/load-smoke.mjs'])],
];

const results = [];
let failed = 0;
for (const [name, fn] of steps) {
  process.stdout.write(`▶ ${name} … `);
  const { status, out } = fn();
  if (status === 'FAIL') failed++;
  const summary = out.split('\n').filter(Boolean).slice(-3).join(' | ').slice(0, 240);
  console.log(status);
  results.push({ name, status, summary });
}

const icon = (s) => (s === 'PASS' ? '✅' : s === 'SKIP' ? '⚪' : '❌');
const ts = new Date().toISOString();
const md = `---
layout:    default
title:     "Runtime Certification"
nav_exclude: true
permalink: /runtime-certification/
description: "Auto-generated StreetJS runtime certification results from npm run verify:runtime."
---

# StreetJS Runtime Certification

> Auto-generated by \`npm run verify:runtime\` (scripts/audit/verify-runtime.mjs).
> Commit \`${git}\` · ${ts} · Node ${process.version}.
> Tags: ✅ PASS · ⚪ SKIP (no live DB reachable) · ❌ FAIL.

| Check | Result | Evidence (tail) |
|-------|:------:|-----------------|
${results.map((r) => `| ${r.name} | ${icon(r.status)} ${r.status} | \`${r.summary.replace(/\|/g, '/')}\` |`).join('\n')}

**Overall: ${failed === 0 ? '✅ CERTIFIED (no failures)' : `❌ ${failed} FAILED`}**

## Reproduce

\`\`\`bash
npm run build --workspaces --if-present
npm run verify:runtime
\`\`\`

Individual probes live in \`scripts/audit/*.mjs\` and can be run standalone.
Live-DB steps (PostgreSQL/MySQL) require reachable databases; they are marked
SKIP — never silently passed — when no database is available.
`;

writeFileSync('docs/runtime-certification.md', md);
console.log(`\nWrote docs/runtime-certification.md — ${failed === 0 ? 'CERTIFIED' : failed + ' failed'}`);
process.exit(failed === 0 ? 0 : 1);
