// src/channels/ChatChannel.ts
// ChatChannel — auto-generated by `street make:channel`.
//
// A strongly-typed channel definition that binds a typed message union to a
// room, so consumers get compile-time checking of broadcast payloads.

import { type Room, type RealtimeMessage } from '@streetjs/realtime';

/** Typed messages carried by the "chat" channel. */
export type ChatMessage =
  | RealtimeMessage<{ text: string }>;

/** Strongly-typed handle factory for the "chat" channel. */
export class ChatChannel {
  /** The stable channel name this handle broadcasts to. */
  static readonly channelName = 'chat' as const;

  constructor(private readonly room: Room) {}

  /** Deliver a typed {@link ChatMessage} to every member of the room. */
  broadcast(message: ChatMessage): Promise<void> {
    return this.room.broadcast(message);
  }
}
