// src/sdk-gen/typescript.ts
// Generates a minimal TypeScript SDK from an OpenAPI spec.
// Writes two files to outputDir:
//   - types.ts     — TypeScript interfaces derived from operationIds / params
//   - api-client.ts — A typed fetch-based client class
import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
// ─── Helpers ──────────────────────────────────────────────────────────────────
/** Convert a path like `/users/{id}` to a safe TypeScript identifier. */
function pathToIdentifier(path, method) {
    const sanitized = path
        .replace(/^\//, '')
        .replace(/\{(\w+)\}/g, 'By$1')
        .split('/')
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
        .join('');
    return method.toLowerCase() + sanitized;
}
/** Derive a TypeScript interface name from an operationId or path+method. */
function operationTypeName(path, method, op) {
    const base = op.operationId ?? pathToIdentifier(path, method);
    return base.charAt(0).toUpperCase() + base.slice(1);
}
// ─── types.ts generator ───────────────────────────────────────────────────────
function generateTypesSource(spec) {
    const lines = [
        '// Auto-generated by Street SDK Generator — do not edit manually.',
        '',
        '/** Base response wrapper */\nexport interface ApiResponse<T> {',
        '  data: T;',
        '  status: number;',
        '}',
        '',
    ];
    for (const [path, methods] of Object.entries(spec.paths)) {
        for (const [method, op] of Object.entries(methods)) {
            const typeName = operationTypeName(path, method, op);
            // Request params interface
            lines.push(`/** Parameters for ${method.toUpperCase()} ${path} */`);
            lines.push(`export interface ${typeName}Params {`);
            // Path params extracted from the URL template
            const pathParams = [...path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
            for (const param of pathParams) {
                lines.push(`  ${param}: string;`);
            }
            // Additional parameters from spec
            const specParams = (op.parameters ?? []);
            for (const param of specParams) {
                if (!param.name)
                    continue;
                const isPathParam = pathParams.includes(param.name);
                if (!isPathParam) {
                    const optional = param.required === true ? '' : '?';
                    lines.push(`  ${param.name}${optional}: string;`);
                }
            }
            lines.push('}', '');
            // Response interface (generic placeholder)
            lines.push(`/** Response for ${method.toUpperCase()} ${path} */`);
            lines.push(`export interface ${typeName}Response {`);
            lines.push('  [key: string]: unknown;');
            lines.push('}', '');
        }
    }
    return lines.join('\n');
}
// ─── api-client.ts generator ──────────────────────────────────────────────────
function generateClientSource(spec) {
    const importTypes = ['ApiResponse'];
    const methods = [];
    for (const [path, pathMethods] of Object.entries(spec.paths)) {
        for (const [method, op] of Object.entries(pathMethods)) {
            const typeName = operationTypeName(path, method, op);
            importTypes.push(`${typeName}Params`, `${typeName}Response`);
            // Build method body
            const hasBody = ['post', 'put', 'patch'].includes(method.toLowerCase());
            const pathParams = [...path.matchAll(/\{(\w+)\}/g)].map((m) => m[1]);
            // URL interpolation
            let urlExpr = `\`\${this.baseUrl}${path.replace(/\{(\w+)\}/g, '${params.$1}')}\``;
            // Collect query params (non-path params)
            const specParams = (op.parameters ?? []);
            const queryParams = specParams.filter((p) => p.name && !pathParams.includes(p.name));
            let urlBuildLines = [`    const url = ${urlExpr};`];
            if (queryParams.length > 0) {
                urlBuildLines = [
                    `    let url = ${urlExpr};`,
                    `    const qs = new URLSearchParams();`,
                    ...queryParams.map((p) => {
                        const name = p.name;
                        const opt = p.required === true ? '' : `if (params.${name} !== undefined) `;
                        return `    ${opt}qs.append('${name}', String(params.${name}));`;
                    }),
                    `    const qsStr = qs.toString(); if (qsStr) url += '?' + qsStr;`,
                ];
            }
            const bodyArg = hasBody ? ', body?: unknown' : '';
            const fetchOpts = [
                `method: '${method.toUpperCase()}'`,
                `headers: { 'Content-Type': 'application/json', ...this.defaultHeaders }`,
                ...(hasBody ? ['body: body !== undefined ? JSON.stringify(body) : undefined'] : []),
            ].join(', ');
            const summary = op.summary ? `  /** ${op.summary} */\n` : '';
            methods.push(`${summary}  async ${typeName.charAt(0).toLowerCase() + typeName.slice(1)}(params: ${typeName}Params${bodyArg}): Promise<ApiResponse<${typeName}Response>> {`, ...urlBuildLines, `    const res = await fetch(url, { ${fetchOpts} });`, `    const data = await res.json() as ${typeName}Response;`, `    return { data, status: res.status };`, `  }`, '');
        }
    }
    // Deduplicate imports
    const uniqueImports = [...new Set(importTypes)].sort();
    return [
        '// Auto-generated by Street SDK Generator — do not edit manually.',
        `import type { ${uniqueImports.join(', ')} } from './types.js';`,
        '',
        'export class ApiClient {',
        '  constructor(',
        '    private readonly baseUrl: string,',
        '    private readonly defaultHeaders: Record<string, string> = {},',
        '  ) {}',
        '',
        ...methods,
        '}',
        '',
    ].join('\n');
}
// ─── Public API ───────────────────────────────────────────────────────────────
/**
 * Generate a TypeScript SDK from an OpenAPI spec and write the output files
 * to `outputDir`.
 *
 * Files written:
 *   - `<outputDir>/types.ts`      — request/response TypeScript interfaces
 *   - `<outputDir>/api-client.ts` — typed fetch-based `ApiClient` class
 */
export async function generateTypescriptSdk(spec, outputDir) {
    await mkdir(outputDir, { recursive: true });
    const typesSource = generateTypesSource(spec);
    const clientSource = generateClientSource(spec);
    await Promise.all([
        writeFile(join(outputDir, 'types.ts'), typesSource, 'utf8'),
        writeFile(join(outputDir, 'api-client.ts'), clientSource, 'utf8'),
    ]);
}
//# sourceMappingURL=typescript.js.map