// src/cli/generators.ts
// @streetjs/queue — code generators for `make:job` / `make:worker` (Req 15.2,
// 15.3, 15.4, 15.6, 15.7).
//
// Validates a provided name, refuses to overwrite an existing target, and emits
// a typed scaffold that imports only public `@streetjs/queue` symbols and
// compiles under `tsc`. All functions here are pure with respect to the
// filesystem except {@link writeScaffold}, which performs the (guarded) write —
// keeping name-validation and template rendering trivially unit-testable
// without touching disk (task 16.2).

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/** The outcome of a generator invocation. */
export interface GenerateResult {
  /** Path of the file that was (or would be) written. */
  path: string;
  /** The generated source content. */
  contents: string;
}

/**
 * A generator name must be a PascalCase-friendly identifier: a letter followed
 * by letters/digits. This deliberately rejects empty strings, whitespace,
 * dashes/dots, path separators (`/`, `\`), and leading digits, so the name is
 * both a valid TypeScript class identifier and safe to interpolate into a file
 * path (no traversal).
 */
const IDENTIFIER_RE = /^[A-Za-z][A-Za-z0-9]*$/;

/** Default output directory for `make:job` scaffolds. */
export const DEFAULT_JOB_DIR = './jobs';
/** Default output directory for `make:worker` scaffolds. */
export const DEFAULT_WORKER_DIR = './workers';

/** Validate a `make:job` / `make:worker` name (identifier-safe, Req 15.2, 15.7). */
export function isValidGeneratorName(name: string): boolean {
  return typeof name === 'string' && IDENTIFIER_RE.test(name);
}

/** Normalize a validated name to a PascalCase class identifier. */
function toClassName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** Throw a descriptive error when a name fails validation (Req 15.2, 15.7). */
function assertValidName(name: string): void {
  if (!isValidGeneratorName(name)) {
    throw new Error(
      `Invalid generator name: "${name}". Use a PascalCase identifier ` +
        `(a letter followed by letters or digits, e.g. "SendEmail").`,
    );
  }
}

/**
 * Generate a Job scaffold. The template imports only the public `Job` base from
 * `@streetjs/queue` and compiles cleanly under `tsc` (Req 15.4).
 *
 * @param name Validated PascalCase name (also the job `type`).
 * @param dir  Output directory (default `./jobs`).
 */
export function generateJob(name: string, dir: string = DEFAULT_JOB_DIR): GenerateResult {
  assertValidName(name);
  const className = toClassName(name);
  const path = join(dir, `${className}.ts`);
  const contents = `// ${className}.ts — generated by \`street make:job ${name}\`.
import { Job } from '@streetjs/queue';

/**
 * Typed payload for {@link ${className}}.
 *
 * Replace the index signature below with the concrete fields this job carries.
 */
export interface ${className}Payload {
  [key: string]: unknown;
}

/**
 * ${className} background job.
 *
 * Dispatch it through a queue:
 *   await queue.dispatch(new ${className}({ /* payload */ }));
 *
 * Register a handler for it before starting a worker:
 *   queue.registerClass(${className}, async (payload, ctx) => {
 *     // handle the job
 *   });
 */
export class ${className} extends Job<${className}Payload> {
  readonly type = '${className}';
}
`;
  return { path, contents };
}

/**
 * Generate a Worker scaffold. The template imports only public `@streetjs/queue`
 * symbols (`createQueue`, and the `Queue`/`Worker` types) and uses the public
 * `register`/`work` surface, so it compiles cleanly under `tsc` (Req 15.4).
 *
 * @param name Validated PascalCase name.
 * @param dir  Output directory (default `./workers`).
 */
export function generateWorker(name: string, dir: string = DEFAULT_WORKER_DIR): GenerateResult {
  assertValidName(name);
  const className = toClassName(name);
  const path = join(dir, `${className}.ts`);
  const contents = `// ${className}.ts — generated by \`street make:worker ${name}\`.
import { createQueue } from '@streetjs/queue';
import type { Queue, Worker } from '@streetjs/queue';

/**
 * Configure a queue and start a ${className} worker over the configured queues.
 *
 * Run it from the CLI with:
 *   street queue:work --queues default --concurrency 1
 */
export function start${className}(): { queue: Queue; worker: Worker } {
  const queue = createQueue();

  // Register a handler for every job type this worker should process.
  queue.register<unknown>('ExampleJob', async (payload, ctx) => {
    // TODO: handle the job using its typed payload and execution context.
    void payload;
    void ctx;
  });

  const worker = queue.work({ queues: ['default'], concurrency: 1 });
  worker.start();
  return { queue, worker };
}
`;
  return { path, contents };
}

/**
 * Write a generated scaffold to disk, refusing to overwrite an existing target
 * (Req 15.3) and creating a fresh file otherwise (Req 15.6). The parent
 * directory is created as needed. The `wx` flag makes the no-overwrite check
 * atomic; the prior `existsSync` guard yields a friendlier error message.
 *
 * @throws Error when the target file already exists.
 */
export function writeScaffold(result: GenerateResult): void {
  if (existsSync(result.path)) {
    throw new Error(`Refusing to overwrite existing file: ${result.path}`);
  }
  mkdirSync(dirname(result.path), { recursive: true });
  writeFileSync(result.path, result.contents, { encoding: 'utf8', flag: 'wx' });
}
