// src/http/openapi.ts
// Generates OpenAPI 3.1 spec from registered route metadata.

export interface OpenApiRouteInput {
  method: string;
  path: string;
  summary?: string;
  description?: string;
  tags?: string[];
  responses?: Record<string, { description: string; schema?: unknown }>;
}

export function generateOpenApi(routes: OpenApiRouteInput[]): object {
  const paths: Record<string, Record<string, unknown>> = {};

  for (const route of routes) {
    // Convert :param to {param} style
    const openApiPath = route.path.replace(/:([a-zA-Z_][a-zA-Z0-9_]*)/g, '{$1}');

    if (!paths[openApiPath]) {
      paths[openApiPath] = {};
    }

    const parameters: unknown[] = [];
    const paramMatches = route.path.matchAll(/:([a-zA-Z_][a-zA-Z0-9_]*)/g);
    for (const m of paramMatches) {
      parameters.push({
        name: m[1],
        in: 'path',
        required: true,
        schema: { type: 'string' },
      });
    }

    const responseMap: Record<string, unknown> = {};
    if (route.responses) {
      for (const [code, resp] of Object.entries(route.responses)) {
        responseMap[code] = {
          description: resp.description,
          ...(resp.schema ? { content: { 'application/json': { schema: resp.schema } } } : {}),
        };
      }
    } else {
      responseMap['200'] = { description: 'Success' };
    }

    paths[openApiPath][route.method.toLowerCase()] = {
      summary: route.summary ?? `${route.method} ${openApiPath}`,
      ...(route.description ? { description: route.description } : {}),
      ...(route.tags ? { tags: route.tags } : {}),
      ...(parameters.length > 0 ? { parameters } : {}),
      responses: responseMap,
    };
  }

  return {
    openapi: '3.1.0',
    info: {
      title: 'Street API',
      version: '1.0.0',
      description: 'Generated by Street Framework',
    },
    paths,
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
      },
    },
  };
}
