// src/gateways/{{NAME}}.gateway.ts
// {{NAME}} WebSocket gateway — auto-generated by street generate.

import { Injectable, WebSocketGateway } from '@streetjs/core';
import type { StreetContext } from '@streetjs/core';

/**
 * {{NAME}} WebSocket gateway.
 *
 * Handles WebSocket lifecycle events for the {{NAME}} channel.
 * Decorate with `@WebSocketGateway` to register the gateway with the
 * Street WebSocket server at startup.
 */
@Injectable()
@WebSocketGateway()
export class {{NAME}}Gateway {
  /**
   * Called when a new WebSocket client connects.
   */
  async onConnect(ctx: StreetContext): Promise<void> {
    // TODO: Handle client connection.
  }

  /**
   * Called when a message is received from a connected client.
   */
  async onMessage(ctx: StreetContext, message: string | Buffer): Promise<void> {
    // TODO: Handle incoming message.
  }

  /**
   * Called when a WebSocket client disconnects.
   */
  async onDisconnect(ctx: StreetContext): Promise<void> {
    // TODO: Handle client disconnection.
  }
}
