// src/middleware/{{NAME}}.middleware.ts
// {{NAME}} middleware — auto-generated by street generate.

import type { StreetContext, MiddlewareFn } from '@streetjs/core';

/**
 * {{NAME}} middleware.
 *
 * Intercepts every request passing through the router pipeline.
 * Call `next()` to hand control to the next middleware or route handler.
 * Throw or set a response directly to short-circuit the pipeline.
 */
export const {{NAME}}Middleware: MiddlewareFn = async (
  ctx: StreetContext,
  next: () => Promise<void>
): Promise<void> => {
  // TODO: Add {{NAME}} middleware logic here.
  await next();
};
