// src/cli/generators.ts
// @streetjs/events — code generators for `make:event` / `make:listener`.
//
// Validate a name, refuse to overwrite an existing target, and emit a typed
// scaffold that imports only public `@streetjs/events` symbols and compiles
// under `tsc`. Name validation and template rendering are pure (no filesystem),
// so they are trivially unit-testable; `writeScaffold` performs the guarded write.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/** The outcome of a generator invocation. */
export interface GenerateResult {
  /** Path of the file that was (or would be) written. */
  path: string;
  /** The generated source content. */
  contents: string;
}

/** A generator name must be an identifier-safe PascalCase token. */
const IDENTIFIER_RE = /^[A-Za-z][A-Za-z0-9]*$/;

/** Default output directory for `make:event` scaffolds. */
export const DEFAULT_EVENT_DIR = './events';
/** Default output directory for `make:listener` scaffolds. */
export const DEFAULT_LISTENER_DIR = './listeners';

/** Validate a `make:event` / `make:listener` name (identifier-safe). */
export function isValidGeneratorName(name: string): boolean {
  return typeof name === 'string' && IDENTIFIER_RE.test(name);
}

function toClassName(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

/** Convert a PascalCase name into a dot-delimited event name (`UserCreated` → `user.created`). */
function toEventName(name: string): string {
  const withDots = name
    .replace(/([a-z0-9])([A-Z])/g, '$1.$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1.$2');
  return withDots.toLowerCase();
}

function assertValidName(name: string): void {
  if (!isValidGeneratorName(name)) {
    throw new Error(
      `Invalid generator name: "${name}". Use a PascalCase identifier ` +
        `(a letter followed by letters or digits, e.g. "UserCreated").`,
    );
  }
}

/**
 * Generate an event scaffold: a strongly-typed `Event` subclass importing only
 * the public `Event` base from `@streetjs/events`. Compiles cleanly under `tsc`.
 */
export function generateEvent(name: string, dir: string = DEFAULT_EVENT_DIR): GenerateResult {
  assertValidName(name);
  const className = toClassName(name);
  const eventName = toEventName(className);
  const path = join(dir, `${className}.ts`);
  const contents = `// ${className}.ts — generated by \`street make:event ${name}\`.
import { Event } from '@streetjs/events';

/** Typed payload for the {@link ${className}} event. */
export interface ${className}Payload {
  [key: string]: unknown;
}

/**
 * ${className} application event.
 *
 * Publish it:
 *   await events.publish(new ${className}({ ...fields }));
 *   // or: await events.publish('${eventName}', { ...fields });
 */
export class ${className} extends Event<${className}Payload> {
  readonly type = '${eventName}';
}
`;
  return { path, contents };
}

/**
 * Generate a listener scaffold: a function that subscribes a handler on an
 * {@link Events} facade. Imports only public `@streetjs/events` types and
 * compiles cleanly under `tsc`.
 */
export function generateListener(name: string, dir: string = DEFAULT_LISTENER_DIR): GenerateResult {
  assertValidName(name);
  const className = toClassName(name);
  const eventName = toEventName(className);
  const path = join(dir, `${className}Listener.ts`);
  const contents = `// ${className}Listener.ts — generated by \`street make:listener ${name}\`.
import type { Events, Unsubscribe } from '@streetjs/events';

/**
 * Register the ${className} listener on an {@link Events} facade. Returns the
 * unsubscribe handle. Call this during application/plugin startup.
 */
export function register${className}Listener(events: Events): Unsubscribe {
  return events.on('${eventName}', async (payload, ctx) => {
    // TODO: handle the event using its payload and execution context.
    void payload;
    void ctx;
  });
}
`;
  return { path, contents };
}

/**
 * Write a generated scaffold to disk, refusing to overwrite an existing target
 * and creating a fresh file otherwise. The parent directory is created as
 * needed; the `wx` flag makes the no-overwrite check atomic.
 *
 * @throws Error when the target file already exists.
 */
export function writeScaffold(result: GenerateResult): void {
  if (existsSync(result.path)) {
    throw new Error(`Refusing to overwrite existing file: ${result.path}`);
  }
  mkdirSync(dirname(result.path), { recursive: true });
  writeFileSync(result.path, result.contents, { encoding: 'utf8', flag: 'wx' });
}
