// src/gateways/{{NAME}}Gateway.ts
// {{NAME}}Gateway — auto-generated by `street make:gateway`.
//
// A typed Gateway that groups realtime event handlers for a set of rooms,
// wired to the public `Realtime` facade. It imports only public
// `@streetjs/realtime` symbols so the generated file compiles cleanly under the
// project's TypeScript configuration.

import { type Realtime, type Room, type Member, type RealtimeMessage } from '@streetjs/realtime';

/**
 * The connection type accepted by {@link Room.join}/{@link Room.leave}, derived
 * from the public `Room` API so the gateway needs no non-public import.
 */
type GatewayConnection = Parameters<Room['join']>[1];

/** Typed events broadcast by {@link {{NAME}}Gateway} over the "{{CHANNEL}}" room. */
export type {{NAME}}Event =
  | RealtimeMessage<{ text: string }>;

/**
 * Groups realtime event handlers for the {{NAME}} feature. Construct it with the
 * application's {@link Realtime} facade and route your transport events to its
 * handler methods.
 */
export class {{NAME}}Gateway {
  /** The stable room name this gateway operates on. */
  static readonly room = '{{CHANNEL}}' as const;

  constructor(private readonly realtime: Realtime) {}

  /** Add a member's connection to the gateway's room. */
  onJoin(member: Member, conn: GatewayConnection): Promise<void> {
    return this.realtime.room({{NAME}}Gateway.room).join(member, conn);
  }

  /** Remove a member's connection from the gateway's room. */
  onLeave(member: Member, conn: GatewayConnection): Promise<void> {
    return this.realtime.room({{NAME}}Gateway.room).leave(member, conn);
  }

  /**
   * Broadcast a typed message to every member of the room, excluding the
   * sending member's own connections.
   */
  onMessage(member: Member, text: string): Promise<void> {
    const event: {{NAME}}Event = { type: 'message', payload: { text } };
    return this.realtime.room({{NAME}}Gateway.room).broadcast(event, {
      exceptMemberId: member.id,
    });
  }
}
