source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "~> 0.10"
gem "webrick", "~> 1.8"   # required for Ruby 3.x

# Required Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed",             "~> 0.17"
  gem "jekyll-seo-tag",          "~> 2.8"
  gem "jekyll-sitemap",          "~> 1.4"
  gem "jekyll-relative-links",   "~> 0.6"
end
